Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Definición de la red privada
  config.vm.network "private_network", ip: "192.168.56.10"

  # Forja de recursos físicos
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Script de Ignición Solar (Aprovisionamiento)
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl
  SHELL
end